require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PostsController do

  # This should return the minimal set of attributes required to create a valid
  # Post. As you add validations to Post, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "title" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PostsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    let(:post) { FactoryGirl.create :post }

    it "assigns all posts as @posts" do
      get :index
      assigns(:posts).should eq([post])
    end

    it "renders the :index view" do
      get :index
      response.should render_template :index
    end
  end

  describe "GET show" do
    let(:post) { FactoryGirl.create :post }
    
    it "assigns the requested post as @post" do
      get :show, {:id => post}
      assigns(:post).should eq(post)
    end

    it "renders the #show view" do
      get :show, {id: post}
      response.should render_template :show
    end
  end

  describe "GET new" do
    
    it "assigns a new post as @post" do
      get :new
      assigns(:post).should be_a_new(Post)
    end
  end

  describe "GET edit" do
    let(:post) { FactoryGirl.create :post }
    
    it "assigns the requested post as @post" do
      get :edit, {:id => post}
      assigns(:post).should eq(post)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Post" do
        expect {
          post :create, {:post => FactoryGirl.build(:post)}
        }.to change(Post, :count).by(1)
      end

      it "assigns a newly created post as @post" do
        post :create, {:post => FactoryGirl.build(:post)}
        assigns(:post).should be_a(Post)
        assigns(:post).should be_persisted
      end

      it "redirects to the created post" do
        post :create, {:post => FactoryGirl.build(:post)}
        response.should redirect_to(Post.last)
      end
    end

    describe "with invalid params" do

      it "assigns a newly created but unsaved post as @post" do
        # Trigger the behavior that occurs when invalid params are submitted
        Post.any_instance.stub(:save).and_return(false)
        post :create, {:post => FactoryGirl.build(:invalid_post)}
        assigns(:post).should be_a_new(Post)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Post.any_instance.stub(:save).and_return(false)
        post :create, {:post => FactoryGirl.build(:invalid_post)}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:post) { FactoryGirl.create :post }
      
      it "updates the requested post" do 
        pending       
        # Assuming there are no other posts in the database, this
        # specifies that the Post created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Post.any_instance.should_receive(:update).with(post)
        put :update, {:id => post, :post => post}
      end

      it "assigns the requested post as @post" do
        pending
        put :update, {:id => post, :post => post}
        assigns(:post).should eq(post)
      end

      it "redirects to the post" do
        pending
        put :update, {:id => post, :post => post}
        response.should redirect_to(post)
      end
    end

    describe "with invalid params" do

      let(:invalid_post) { FactoryGirl.build :invalid_post }

      it "assigns the post as @post" do
        pending
        # Trigger the behavior that occurs when invalid params are submitted
        Post.any_instance.stub(:save).and_return(false)
        put :update, {:id => invalid_post, :post => invalid_post}
        assigns(:post).should eq(post)
      end

      it "re-renders the 'edit' template" do
        pending
        # Trigger the behavior that occurs when invalid params are submitted
        Post.any_instance.stub(:save).and_return(false)
        put :update, {:id => invalid_post, :post => invalid_post}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    let(:post) { FactoryGirl.create :post }

    it "destroys the requested post" do
      pending
      expect {
        delete :destroy, {:id => post}
      }.to change(Post, :count).by(-1)
    end

    it "redirects to the posts list" do
      pending
      delete :destroy, {:id => post}
      response.should redirect_to(posts_url)
    end
  end

end
